#make -f Makefile
#leetcode: string_leet.cpp struct_defines_leet.h
#	g++ -std=c++11 string_leet.cpp -o leetcode

leetcode: tree_leet.cpp struct_defines_leet.h
	g++ -std=c++11 tree_leet.cpp -o leetcode
